//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34003 版自动生成。
// 
#pragma warning disable 1591

namespace SZMA.Core.CSrvUserValid {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CSrvUserValidSoap", Namespace="http://tempuri.org/")]
    public partial class CSrvUserValid : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetNewUPGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrivilageValidOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserList2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserListOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserPasswordValidOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllDeptOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllPrivilageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CSrvUserValid() {
            this.Url = global::SZMA.Core.Properties.Settings.Default.SZMA_Core_CSrvUserValid_CSrvUserValid;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetNewUPGroupCompletedEventHandler GetNewUPGroupCompleted;
        
        /// <remarks/>
        public event PrivilageValidCompletedEventHandler PrivilageValidCompleted;
        
        /// <remarks/>
        public event GetUsersCompletedEventHandler GetUsersCompleted;
        
        /// <remarks/>
        public event GetUserList2CompletedEventHandler GetUserList2Completed;
        
        /// <remarks/>
        public event GetUserListCompletedEventHandler GetUserListCompleted;
        
        /// <remarks/>
        public event UserPasswordValidCompletedEventHandler UserPasswordValidCompleted;
        
        /// <remarks/>
        public event GetAllDeptCompletedEventHandler GetAllDeptCompleted;
        
        /// <remarks/>
        public event GetAllUserCompletedEventHandler GetAllUserCompleted;
        
        /// <remarks/>
        public event GetAllPrivilageCompletedEventHandler GetAllPrivilageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNewUPGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CUPGroup GetNewUPGroup(string fmyUserID) {
            object[] results = this.Invoke("GetNewUPGroup", new object[] {
                        fmyUserID});
            return ((CUPGroup)(results[0]));
        }
        
        /// <remarks/>
        public void GetNewUPGroupAsync(string fmyUserID) {
            this.GetNewUPGroupAsync(fmyUserID, null);
        }
        
        /// <remarks/>
        public void GetNewUPGroupAsync(string fmyUserID, object userState) {
            if ((this.GetNewUPGroupOperationCompleted == null)) {
                this.GetNewUPGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewUPGroupOperationCompleted);
            }
            this.InvokeAsync("GetNewUPGroup", new object[] {
                        fmyUserID}, this.GetNewUPGroupOperationCompleted, userState);
        }
        
        private void OnGetNewUPGroupOperationCompleted(object arg) {
            if ((this.GetNewUPGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewUPGroupCompleted(this, new GetNewUPGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrivilageValid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PrivilageValid(string fsPrivilageID, CUPGroup foUPG, ref string fsAreaID) {
            object[] results = this.Invoke("PrivilageValid", new object[] {
                        fsPrivilageID,
                        foUPG,
                        fsAreaID});
            fsAreaID = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PrivilageValidAsync(string fsPrivilageID, CUPGroup foUPG, string fsAreaID) {
            this.PrivilageValidAsync(fsPrivilageID, foUPG, fsAreaID, null);
        }
        
        /// <remarks/>
        public void PrivilageValidAsync(string fsPrivilageID, CUPGroup foUPG, string fsAreaID, object userState) {
            if ((this.PrivilageValidOperationCompleted == null)) {
                this.PrivilageValidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrivilageValidOperationCompleted);
            }
            this.InvokeAsync("PrivilageValid", new object[] {
                        fsPrivilageID,
                        foUPG,
                        fsAreaID}, this.PrivilageValidOperationCompleted, userState);
        }
        
        private void OnPrivilageValidOperationCompleted(object arg) {
            if ((this.PrivilageValidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrivilageValidCompleted(this, new PrivilageValidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CUser[] GetUsers(string fsPrivilageID, string fsAreaID) {
            object[] results = this.Invoke("GetUsers", new object[] {
                        fsPrivilageID,
                        fsAreaID});
            return ((CUser[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersAsync(string fsPrivilageID, string fsAreaID) {
            this.GetUsersAsync(fsPrivilageID, fsAreaID, null);
        }
        
        /// <remarks/>
        public void GetUsersAsync(string fsPrivilageID, string fsAreaID, object userState) {
            if ((this.GetUsersOperationCompleted == null)) {
                this.GetUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersOperationCompleted);
            }
            this.InvokeAsync("GetUsers", new object[] {
                        fsPrivilageID,
                        fsAreaID}, this.GetUsersOperationCompleted, userState);
        }
        
        private void OnGetUsersOperationCompleted(object arg) {
            if ((this.GetUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersCompleted(this, new GetUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserList2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CUser[] GetUserList2(string sUnitID, string sAreaID, string[] sArrPrivilageID) {
            object[] results = this.Invoke("GetUserList2", new object[] {
                        sUnitID,
                        sAreaID,
                        sArrPrivilageID});
            return ((CUser[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUserList2Async(string sUnitID, string sAreaID, string[] sArrPrivilageID) {
            this.GetUserList2Async(sUnitID, sAreaID, sArrPrivilageID, null);
        }
        
        /// <remarks/>
        public void GetUserList2Async(string sUnitID, string sAreaID, string[] sArrPrivilageID, object userState) {
            if ((this.GetUserList2OperationCompleted == null)) {
                this.GetUserList2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserList2OperationCompleted);
            }
            this.InvokeAsync("GetUserList2", new object[] {
                        sUnitID,
                        sAreaID,
                        sArrPrivilageID}, this.GetUserList2OperationCompleted, userState);
        }
        
        private void OnGetUserList2OperationCompleted(object arg) {
            if ((this.GetUserList2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserList2Completed(this, new GetUserList2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CUser[] GetUserList(string ValidPrivilageID, string UnitID, int AreaID) {
            object[] results = this.Invoke("GetUserList", new object[] {
                        ValidPrivilageID,
                        UnitID,
                        AreaID});
            return ((CUser[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUserListAsync(string ValidPrivilageID, string UnitID, int AreaID) {
            this.GetUserListAsync(ValidPrivilageID, UnitID, AreaID, null);
        }
        
        /// <remarks/>
        public void GetUserListAsync(string ValidPrivilageID, string UnitID, int AreaID, object userState) {
            if ((this.GetUserListOperationCompleted == null)) {
                this.GetUserListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserListOperationCompleted);
            }
            this.InvokeAsync("GetUserList", new object[] {
                        ValidPrivilageID,
                        UnitID,
                        AreaID}, this.GetUserListOperationCompleted, userState);
        }
        
        private void OnGetUserListOperationCompleted(object arg) {
            if ((this.GetUserListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserListCompleted(this, new GetUserListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserPasswordValid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UserPasswordValid(string fsUID, string fsPwd) {
            object[] results = this.Invoke("UserPasswordValid", new object[] {
                        fsUID,
                        fsPwd});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UserPasswordValidAsync(string fsUID, string fsPwd) {
            this.UserPasswordValidAsync(fsUID, fsPwd, null);
        }
        
        /// <remarks/>
        public void UserPasswordValidAsync(string fsUID, string fsPwd, object userState) {
            if ((this.UserPasswordValidOperationCompleted == null)) {
                this.UserPasswordValidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserPasswordValidOperationCompleted);
            }
            this.InvokeAsync("UserPasswordValid", new object[] {
                        fsUID,
                        fsPwd}, this.UserPasswordValidOperationCompleted, userState);
        }
        
        private void OnUserPasswordValidOperationCompleted(object arg) {
            if ((this.UserPasswordValidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserPasswordValidCompleted(this, new UserPasswordValidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllDept", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAllDept(string deptCode) {
            object[] results = this.Invoke("GetAllDept", new object[] {
                        deptCode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllDeptAsync(string deptCode) {
            this.GetAllDeptAsync(deptCode, null);
        }
        
        /// <remarks/>
        public void GetAllDeptAsync(string deptCode, object userState) {
            if ((this.GetAllDeptOperationCompleted == null)) {
                this.GetAllDeptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllDeptOperationCompleted);
            }
            this.InvokeAsync("GetAllDept", new object[] {
                        deptCode}, this.GetAllDeptOperationCompleted, userState);
        }
        
        private void OnGetAllDeptOperationCompleted(object arg) {
            if ((this.GetAllDeptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllDeptCompleted(this, new GetAllDeptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAllUser(string deptCode) {
            object[] results = this.Invoke("GetAllUser", new object[] {
                        deptCode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllUserAsync(string deptCode) {
            this.GetAllUserAsync(deptCode, null);
        }
        
        /// <remarks/>
        public void GetAllUserAsync(string deptCode, object userState) {
            if ((this.GetAllUserOperationCompleted == null)) {
                this.GetAllUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllUserOperationCompleted);
            }
            this.InvokeAsync("GetAllUser", new object[] {
                        deptCode}, this.GetAllUserOperationCompleted, userState);
        }
        
        private void OnGetAllUserOperationCompleted(object arg) {
            if ((this.GetAllUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllUserCompleted(this, new GetAllUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllPrivilage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAllPrivilage(string privilagetype) {
            object[] results = this.Invoke("GetAllPrivilage", new object[] {
                        privilagetype});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllPrivilageAsync(string privilagetype) {
            this.GetAllPrivilageAsync(privilagetype, null);
        }
        
        /// <remarks/>
        public void GetAllPrivilageAsync(string privilagetype, object userState) {
            if ((this.GetAllPrivilageOperationCompleted == null)) {
                this.GetAllPrivilageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPrivilageOperationCompleted);
            }
            this.InvokeAsync("GetAllPrivilage", new object[] {
                        privilagetype}, this.GetAllPrivilageOperationCompleted, userState);
        }
        
        private void OnGetAllPrivilageOperationCompleted(object arg) {
            if ((this.GetAllPrivilageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllPrivilageCompleted(this, new GetAllPrivilageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CUPGroup {
        
        private CUserLog oUserLogField;
        
        private CUser userField;
        
        private CUserPrivilage[] userPrivilagesField;
        
        private int privilageCountField;
        
        /// <remarks/>
        public CUserLog oUserLog {
            get {
                return this.oUserLogField;
            }
            set {
                this.oUserLogField = value;
            }
        }
        
        /// <remarks/>
        public CUser User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public CUserPrivilage[] UserPrivilages {
            get {
                return this.userPrivilagesField;
            }
            set {
                this.userPrivilagesField = value;
            }
        }
        
        /// <remarks/>
        public int PrivilageCount {
            get {
                return this.privilageCountField;
            }
            set {
                this.privilageCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CUserLog {
        
        private string sUserLogIDField;
        
        private string sRecoTimeField;
        
        private string sObjectIDField;
        
        private string sUserIDField;
        
        private string sMemoInfoListField;
        
        private string sBeforeField;
        
        private string sAfterField;
        
        private string sOperateField;
        
        private string sUserIPField;
        
        private string sComputerNameField;
        
        /// <remarks/>
        public string sUserLogID {
            get {
                return this.sUserLogIDField;
            }
            set {
                this.sUserLogIDField = value;
            }
        }
        
        /// <remarks/>
        public string sRecoTime {
            get {
                return this.sRecoTimeField;
            }
            set {
                this.sRecoTimeField = value;
            }
        }
        
        /// <remarks/>
        public string sObjectID {
            get {
                return this.sObjectIDField;
            }
            set {
                this.sObjectIDField = value;
            }
        }
        
        /// <remarks/>
        public string sUserID {
            get {
                return this.sUserIDField;
            }
            set {
                this.sUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string sMemoInfoList {
            get {
                return this.sMemoInfoListField;
            }
            set {
                this.sMemoInfoListField = value;
            }
        }
        
        /// <remarks/>
        public string sBefore {
            get {
                return this.sBeforeField;
            }
            set {
                this.sBeforeField = value;
            }
        }
        
        /// <remarks/>
        public string sAfter {
            get {
                return this.sAfterField;
            }
            set {
                this.sAfterField = value;
            }
        }
        
        /// <remarks/>
        public string sOperate {
            get {
                return this.sOperateField;
            }
            set {
                this.sOperateField = value;
            }
        }
        
        /// <remarks/>
        public string sUserIP {
            get {
                return this.sUserIPField;
            }
            set {
                this.sUserIPField = value;
            }
        }
        
        /// <remarks/>
        public string sComputerName {
            get {
                return this.sComputerNameField;
            }
            set {
                this.sComputerNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CUserPrivilage {
        
        private CUserLog userLogField;
        
        private string userIDField;
        
        private string privilageIDField;
        
        private string areaIDField;
        
        private string areaNameField;
        
        private int stateField;
        
        private string privilageNameField;
        
        private string privilageTypeField;
        
        private string typeNameField;
        
        /// <remarks/>
        public CUserLog UserLog {
            get {
                return this.userLogField;
            }
            set {
                this.userLogField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string PrivilageID {
            get {
                return this.privilageIDField;
            }
            set {
                this.privilageIDField = value;
            }
        }
        
        /// <remarks/>
        public string AreaID {
            get {
                return this.areaIDField;
            }
            set {
                this.areaIDField = value;
            }
        }
        
        /// <remarks/>
        public string AreaName {
            get {
                return this.areaNameField;
            }
            set {
                this.areaNameField = value;
            }
        }
        
        /// <remarks/>
        public int State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string PrivilageName {
            get {
                return this.privilageNameField;
            }
            set {
                this.privilageNameField = value;
            }
        }
        
        /// <remarks/>
        public string PrivilageType {
            get {
                return this.privilageTypeField;
            }
            set {
                this.privilageTypeField = value;
            }
        }
        
        /// <remarks/>
        public string TypeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CUser {
        
        private int userFlagField;
        
        private string pIDField;
        
        private int validField;
        
        private CUserLog userLogField;
        
        private string userIPField;
        
        private string computerNameField;
        
        private string userIDField;
        
        private string nameField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string passwordField;
        
        private string unitIDField;
        
        private string unitField;
        
        private string xunChaZuField;
        
        private int isManagerField;
        
        private string emailField;
        
        private string phonenumberField;
        
        private string unitNameField;
        
        private string deptTypeField;
        
        /// <remarks/>
        public int UserFlag {
            get {
                return this.userFlagField;
            }
            set {
                this.userFlagField = value;
            }
        }
        
        /// <remarks/>
        public string PID {
            get {
                return this.pIDField;
            }
            set {
                this.pIDField = value;
            }
        }
        
        /// <remarks/>
        public int Valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        public CUserLog UserLog {
            get {
                return this.userLogField;
            }
            set {
                this.userLogField = value;
            }
        }
        
        /// <remarks/>
        public string UserIP {
            get {
                return this.userIPField;
            }
            set {
                this.userIPField = value;
            }
        }
        
        /// <remarks/>
        public string ComputerName {
            get {
                return this.computerNameField;
            }
            set {
                this.computerNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string UnitID {
            get {
                return this.unitIDField;
            }
            set {
                this.unitIDField = value;
            }
        }
        
        /// <remarks/>
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        public string XunChaZu {
            get {
                return this.xunChaZuField;
            }
            set {
                this.xunChaZuField = value;
            }
        }
        
        /// <remarks/>
        public int IsManager {
            get {
                return this.isManagerField;
            }
            set {
                this.isManagerField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Phonenumber {
            get {
                return this.phonenumberField;
            }
            set {
                this.phonenumberField = value;
            }
        }
        
        /// <remarks/>
        public string UnitName {
            get {
                return this.unitNameField;
            }
            set {
                this.unitNameField = value;
            }
        }
        
        /// <remarks/>
        public string DeptType {
            get {
                return this.deptTypeField;
            }
            set {
                this.deptTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetNewUPGroupCompletedEventHandler(object sender, GetNewUPGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewUPGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewUPGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CUPGroup Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CUPGroup)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void PrivilageValidCompletedEventHandler(object sender, PrivilageValidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrivilageValidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrivilageValidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string fsAreaID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetUsersCompletedEventHandler(object sender, GetUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CUser[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CUser[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetUserList2CompletedEventHandler(object sender, GetUserList2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserList2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserList2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CUser[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CUser[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetUserListCompletedEventHandler(object sender, GetUserListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CUser[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CUser[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void UserPasswordValidCompletedEventHandler(object sender, UserPasswordValidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserPasswordValidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserPasswordValidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetAllDeptCompletedEventHandler(object sender, GetAllDeptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllDeptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllDeptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetAllUserCompletedEventHandler(object sender, GetAllUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetAllPrivilageCompletedEventHandler(object sender, GetAllPrivilageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllPrivilageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllPrivilageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591